name: Java Rest Assured API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "qa"
        type: choice
        options:
          - dev
          - qa
          - prod
          - devSM

permissions:
  contents: write   # ⭐ REQUIRED for gh-pages push

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run API Tests
        run: mvn clean test -Denv=${{ github.event.inputs.env || 'devSM' }}

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      # -----------------------------
      # Deploy Allure Report to GitHub Pages
      # -----------------------------
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        run: |
          git fetch origin || true
          git checkout gh-pages || git checkout -b gh-pages

          # Clean branch but keep .git
          find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +

          # Check if the directory exists before copying
          if [ -d "target/site/allure-maven" ]; then
              cp -r target/site/allure-maven/* .
          else
              echo "Directory target/site/allure-maven does not exist. Skipping file copy."
              exit 1
          fi
          
          touch .nojekyll

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          if git commit -m "Update Allure report"; then
              git push origin gh-pages
          else
              echo "No changes to commit"
          fi

      # -----------------------------
      # Print Allure Report URL
      # -----------------------------
      - name: Print Allure Report URL
        run: |
          OWNER=${GITHUB_REPOSITORY%/*}
          REPO=${GITHUB_REPOSITORY#*/}
          echo "✅ Allure Report URL:"
          echo "https://$OWNER.github.io/$REPO/"