name: Java Rest Assured API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "qa"
        type: choice
        options:
          - dev
          - qa
          - prod
          - devSM

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run API Tests
        run: mvn clean test -Denv=${{ github.event.inputs.env || 'devSM' }}

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      # -----------------------------
      # Deploy Allure Report to GitHub Pages
      # -----------------------------
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout -b gh-pages

          rm -rf *
          cp -r target/site/allure-maven/* .

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages

      # -----------------------------
      # Print Allure Report URL
      # -----------------------------
      - name: Print Allure Report URL
        run: |
          OWNER=${GITHUB_REPOSITORY%/*}
          REPO=${GITHUB_REPOSITORY#*/}
          echo "âœ… Allure Report URL:"
          echo "https://$OWNER.github.io/$REPO/"
