name: Java Rest Assured API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "qa"
        type: choice
        options:
          - dev
          - qa
          - prod
          - devSM

permissions:
  contents: write

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # ðŸ”¥ REQUIRED

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Clean old Allure results
        run: rm -rf target/allure-results

      - name: Run API Tests
        run: mvn test -Denv=${{ github.event.inputs.env || 'devSM' }}

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        run: |
          mkdir -p /tmp/allure-report
          cp -r target/site/allure-maven-plugin/* /tmp/allure-report/

          git reset --hard
          git fetch origin || true
          git checkout gh-pages || git checkout -b gh-pages

          for item in * .*; do
            if [ "$item" != "." ] && [ "$item" != ".." ] && [ "$item" != ".git" ]; then
              rm -rf "$item"
            fi
          done

          cp -r /tmp/allure-report/* .
          touch .nojekyll

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Publish Allure report"
          git push origin gh-pages
